### ISSUE TITLE
Add graze.com to our users

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow.github.com#130]

**Comment by yalisassoon** [comment]
COOL! Did you spot them parsing the CF logs?

On Tue, Apr 7, 2015 at 7:45 PM, Alexander Dean <notifications@github.com>
wrote:

> Assigned #130 <https://github.com/snowplow/snowplow.github.com/issues/130>
> to @yalisassoon <https://github.com/yalisassoon>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow.github.com/issues/130#event-275572373>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by alexanderdean** [comment]
Yep I did!
