### ISSUE TITLE
Add ability to scroll up and down within visualization

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow.github.com#168]
Would be nice if this could be done via buttons on the visualizaiton, and with the keyboard / mouse. (Or swiping on e.g. a mobile phone)

**Comment by galvanic** [comment]
Implemented via mouse (and possibly mobile touch - depends on how d3 handles this): [feat: add zoom and pan directly on chart](https://github.com/snowplow/d3-attribution-visualization/commit/112053753d7df33709d414753cf3f221894afd2d)

**Comment by yalisassoon** [comment]
I think we need some buttons or an onscreen scroll bar (maybe on the right border of the visualization) - as on my mac there's no way to scroll up and down. (Which is weird because in the version you showed me I remember it being possible...)

**Comment by galvanic** [comment]
Added arrows: [feat: new arrows to move the viewport up and down](https://github.com/snowplow/d3-attribution-visualization/commit/be44617c968e01d597c6e9cdc59b0700e9354888)

Can view live [here](http://bl.ocks.org/galvanic/raw/2eb5043ea7c2dd845975/be44617c968e01d597c6e9cdc59b0700e9354888/) (currently not yet implemented in GTM)
