### ISSUE TITLE
Add an explanation to the blog post of how a user should interact with it

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow.github.com#169]
This is the key thing that makes the visualization so special - so let's shout about / make sure a reader understands it and engages with the graph!

**Comment by galvanic** [comment]
I've added a paragraph: [https://github.com/galvanic/snowplow.github.com/commit/749c8b9fb8cecb961007641050b2f50a7fa33e1a]()

Let me know if it's not clear !
