### ISSUE TITLE
I'm not sure that drawing the ribbon works for me...

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow.github.com#170]
Can't seem to get it working - am I being a muppet?

**Comment by yalisassoon** [comment]
I can drag teh top and bottom of the existing ribbon up and down, but can't redraw the ribbon from scratch

**Comment by yalisassoon** [comment]
It works now!

**Comment by yalisassoon** [comment]
Ah figured it out! It works if you draw it where it doesn't already exist... This needs some additional explanation in the post, in the section where you describe how to interact with the visualization

**Comment by galvanic** [comment]
Closed since this is the same as: https://github.com/snowplow/snowplow.github.com/issues/169
