### ISSUE TITLE
Make it so that the visualization renders on the main blog page

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow.github.com#171]
Currently it only renders on the main `/blog/2015/06/30/visualizing-marketing-attribution-data-with-d3js/` page, not on the `/blog/`. I suspect this is simply a case of updating the GTM tag rule so that the JS loads on that page as well...

**Comment by galvanic** [comment]
Yes, I've added a new trigger and added this trigger to the tag.
