### ISSUE TITLE
Can we update the data set so that each colour repesents 'Marketing channel X touched'

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow.github.com#176]
The whole language of 'Ad #1 displayed' 'Ad #2 clicked' is confusing...

**Comment by galvanic** [comment]
![screen shot 2015-06-30 at 10 24 28](https://cloud.githubusercontent.com/assets/2991910/8427821/40ca4ae2-1f12-11e5-9002-5cdacce66ae6.png)
Is this better ?

**Comment by yalisassoon** [comment]
Love it!

On Tue, Jun 30, 2015 at 10:25 AM, justine <notifications@github.com> wrote:

> [image: screen shot 2015-06-30 at 10 24 28]
> <https://cloud.githubusercontent.com/assets/2991910/8427821/40ca4ae2-1f12-11e5-9002-5cdacce66ae6.png>
> Is this better ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow.github.com/issues/176#issuecomment-117075264>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by galvanic** [comment]
Commit: [refactor: Change legend texts (titles and keys)](https://github.com/snowplow/d3-attribution-visualization/commit/51efa4985bea3f969eb61e406876f16fc854e2ee)

Specific text can be changed [here](https://github.com/snowplow/d3-attribution-visualization/blob/51efa4985bea3f969eb61e406876f16fc854e2ee/generateData.js#L12)
