### ISSUE TITLE
Add an annotated screenshot of an individual journey to the blog post

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow.github.com#177]
Where I've added `<!--JUSTINE! INSERT AN ANNOTATED SCREENSHOT HERE -->`.

This should be a journey with 3-4 steps, and each step annotated Marketing Channel A touched, Marketing Channel B touched, Marketing Channel C touched...

**Comment by galvanic** [comment]
Done: [New pictures for d3 blog post](https://github.com/snowplow/snowplow.github.com/commit/ca63617588f314b9baf2f93bca693ccaaac8b91e)
