### ISSUE TITLE
Insert a screenshot illustrating the difference between highly trafficked and lowly trafficked journeys

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow.github.com#178]
The screenshot shoudl contain two journeys, one 'fat' (highly trafficked) and one thin (lowly trafficked).

Please insert it where I've stubbed `<!--JUSTINE! INSERT A SCREENSHOT OF TWO JOURNEYS, ONE HIGHLY TRAFFICKED AND ONE WITH LOW TRAFFIC LEVELS, HERE-->`

**Comment by galvanic** [comment]
Done: [New pictures for d3 blog post](https://github.com/snowplow/snowplow.github.com/commit/ca63617588f314b9baf2f93bca693ccaaac8b91e)
