### ISSUE TITLE
Broken links in blog's sidebar

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow.github.com#266]
Our [blog](http://snowplowanalytics.com/blog/)'s sidebar references categories by their _titles_ and not by the pages _names_ thus forming broken URLs. For example, the category [Inside the Plow](http://snowplowanalytics.com/blog/Inside%20the%20Plow) referes to the page in the URL's path as "Inside the Plow" instead of "inside-the-plow". Also bear in mind that URLs on GitHub are **case-sensitive**.

**Comment by yalisassoon** [comment]
Thansk for raising @ihortom - fixed

**Comment by ihortom** [comment]
@yalisassoon - It doesn't look fixed to me. Clicking on the link (in Chrome) downloads the page instead of redirecting to the intended page. Also, in IE (10) and Firefox sidebar isn't displayed at all (Window 7).

**Comment by bogaert** [comment]
The initial fix caused Jekyll to fail in Vagrant (redirects need to have a trailing slash).

In the past, Jekyll converted the categories variable to lowercase. Now it doesn't, which caused the sidebar to link to non-existing pages.

Note that the categories are now case sensitive (Jekyll is quite limited so there's not much else we can do).
