### ISSUE TITLE
Add event schedule to website

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow.github.com#283]
2016 schedule of where you can meet the Snowplow team in person, including:

* Snowplow and other meetups (e.g. Unified Log)
* Unconferences
* Conferences where Snowplowers are attending/speaking

**Comment by alexanderdean** [comment]
@yalisassoon , @idanby1 can you update this ticket with the known events so far...

**Comment by bogaert** [comment]
- New York
- Boston
- Measurecamp later in 2016

**Comment by bogaert** [comment]
Quick implementation: http://snowplowanalytics.com/events/

The only link to this page is in the footer. I can also add it to the top menu, but that might make it too crowded?

**Comment by alexanderdean** [comment]
Footer is good methinks
