### ISSUE TITLE
Fix image for Snowplow Mini blog post

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow.github.com#301]

**Comment by bogaert** [comment]
What's wrong?

**Comment by alexanderdean** [comment]
The Austen Powers image doesn't render?

**Comment by chuwy** [comment]
I can see it.

**Comment by bogaert** [comment]
So can I, strange.

**Comment by alexanderdean** [comment]
Works in Chrome, not working in my Firefox. Can somebody try in Firefox?

**Comment by alexanderdean** [comment]
Firefox says the image contains errors
