### ISSUE TITLE
[Discourse] Remove sticky header

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow.github.com#320]
On small screens (1280x800) header takes almost 15% of viewport while not adding any useful information IMO. I'm actually using Chrome extension with custom CSS to remove it, but I think it may improve UI for all users.

**Comment by bogaert** [comment]
I agree. This is the default template (with some tweaks to make it look a bit more like our website), but I'd like for Discourse to have the same header as our website.

Because we will redesign the website in the next couple of months anyway, it would make sense to wait until then.

**Comment by bogaert** [comment]
Done.
