### ISSUE TITLE
Figure out why Snowplow tracking is so slow to fire from Discourse pages

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow.github.com#351]
From the Discourse homepage they fire as normal, but they are super slow on the individual post pages.

**Comment by alexanderdean** [comment]
That's odd, /cc @chuwy

**Comment by bogaert** [comment]
@yalisassoon Do I remember correctly it that you resolved this?

**Comment by yalisassoon** [comment]
Yes - closing
